yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from .views import (
    index,
    group_posts,
    profile,
    post_detail,
    post_create,
    post_edit
)


app_name = 'posts'

urlpatterns = [
    path('', index, name='index'),
    path('group/<slug:slug>/', group_posts, name='group_posts'),
    path('profile/<str:username>/', profile, name='profile'),
    path('posts/<int:post_id>/', post_detail, name='post_detail'),
    path('create/', post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', post_edit, name='post_edit')
]

yatube/users/urls.py
from django.urls import path
from django.contrib.auth.views import (LogoutView,
                                       LoginView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView
        .as_view(template_name='users/password_change_form.html'),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView
        .as_view(template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView
        .as_view(template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView
        .as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView
        .as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView
        .as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    )
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about'))
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    """Модель группы"""
    title = models.CharField('Имя группы', max_length=200)
    slug = models.SlugField('Идентификатор', unique=True)
    description = models.TextField('Описание группы', max_length=250)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(models.Model):
    """Модель поста"""
    text = models.TextField('Текст')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Пользователь'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group']
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относится пост',
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email'
        )

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Post, Group, User


def paginate_posts(request, posts):
    """Вспомогательная функция для создания объекта Paginator"""
    return Paginator(posts, 10).get_page(request.GET.get('page'))


def index(request):
    """Отображение всех последних 10 постов"""
    return render(
        request,
        'posts/index.html',
        {'page_obj': paginate_posts(request, Post.objects.all())}
    )


def group_posts(request, slug):
    """Отображение постов конкретной группы"""
    group = get_object_or_404(Group, slug=slug)
    return render(request, 'posts/group_list.html', {
        'group': group,
        'page_obj': paginate_posts(request, group.posts.all()),
    })


def profile(request, username):
    """Отображение профиля конкретного пользователя"""
    author = get_object_or_404(User, username=username)
    return render(request, 'posts/profile.html', {
        'page_obj': paginate_posts(request, author.posts.all()),
        'author': author,
    })


def post_detail(request, post_id):
    """Отображение информации конкретного поста"""
    post = get_object_or_404(Post, id=post_id)
    context = {
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """Создание нового поста"""
    form = PostForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request, post_id):
    """Изменение поста"""
    is_edit = True
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail')
    form = PostForm(request.POST or None, instance=post)
    if not form.is_valid():
        context = {
            'form': form,
            'is_edit': is_edit
        }
        return render(request, 'posts/create_post.html', context)
    post = form.save()
    return redirect('posts:post_detail', post_id)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/about/templates/about/author.html
{% extends "base.html" %}
{% load static %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<section class="lead py-3">
    <div class="container">
      <h1 class="section-title">Совсем немного обо мне</h1>
      <p>Меня зовут, Марат. И программирование - это мое хобби</p>
      <div>
        <div class="row py-3">
          <div class="col-md-4">
            <img src="{% static 'img/about/desktop.jpg' %}" width="400" height="250" >
          </div>
          <div class="col-md-4">
            <h5>Зачем мне это...</h5>
            <p>Я всегда пытался изучать, что-то новое. Сначала выучил два языка (английский и испанский). Теперь решил изучить разные языки программирования. Когда выбирал в каком направлении развиваться, то сначала обратил внимание на Data Science. Но, когда попробовла Web-программрование понял, что это то, чем бы я хотел заниматься профессионально. Теперь развиваюсь в данной направлении.</p>
          </div>
          <div class="col">
            <h4>Ссылки</h4>
            <ul class="icon-list">
              <li><a href="https://github.com/Filin1985" target="_blank">GitHub</a></li>
              <li><a href="https://www.romacoder.com/index.html" target="_blank">Web-сайт</a></li>
              <li><a href="https://hh.ru/resume/d25ce8d4ff097522830039ed1f524e35697851" target="_blank">Резюме</a></li>
              <li><a href="https://www.linkedin.com/in/marat-ikhsanov-75b660118/" target="_blank">LinkedIn</a></li>
            </ul>
          </div>
        </div>
        <div>
            <h4>Мои проекты</h4>
            <div class="card mb-3">
                <div class="row g-0">
                  <div class="col-md-4">
                    <img src="{% static 'img/about/project1.jpg' %}" width="200" height="200" class="img-fluid rounded-start" alt="...">
                    </div>
                      <div class="col-md-8">
                        <div class="card-body">
                          <h5 class="card-title">Проект - BlackFox</h5>
                          <p class="card-text">Данный проект сделан для фитнес клуба. Применяемые технологии HTML, CSS, JS</p>
                          <p class="card-text"><a href="https://gracious-thompson-c3858e.netlify.app/" class="item-text-title" target="_blank">Ссылка на проект</a></p>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %} 

yatube/about/templates/about/tech.html
{% extends "base.html" %}
{% load static %}
{% block title %}Технологии{% endblock %}
{% block content %}

<section class="lead py-3">
    <div class="container">
      <h1 class="section-title">Технологии, которые я применяю</h1>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Python
            </li>
            <li class="list-group-item">
              Django
            </li>
            <li class="list-group-item">
              Bootstrap
            </li>
            <li class="list-group-item">
              CSS
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>Текст страницы "Технологии"</p>
        </article>
      </div>
    </div>
  </section>

{% endblock %}

yatube/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image" />
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="{% static 'img/fav/apple-touch-icon.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="{% static 'img/fav/favicon-32x32.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="{% static 'img/fav/favicon-16x16.png' %}"
    />
    <meta name="msapplication-TileColor" content="#000" />
    <meta name="theme-color" content="#ffffff" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>
    <header>{% include 'includes/header.html' %}</header>
    {% include 'includes/error_page.html' %}
    <main>
      {% block content %} Пока здесь ничего нет {% endblock content %}
    </main>

    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/error_page.html
  {% for message in messages %}
    <div class="container alert {{ message.tags }} alert-dismissible" role="alert">
      {{ message }}
    </div>
  {% endfor %}

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img
        src="{% static 'img/logo.png' %}"
        width="30"
        height="30"
        class="d-inline-block align-top"
        alt=""
      />
      <span style="color: red">Ya</span>tube
    </a>
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a
            class="nav-link {% if view_name == 'about:author' %}active{% endif %}"
            href="{% url 'about:author' %}"
            >Об авторе</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link 
            {% if view_name == 'about:tech' %}
                active
            {% endif %}"
            href="{% url 'about:tech' %}"
            >Технологии</a
          >
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a
              class="nav-link {% if view_name == 'posts:profile' %}active{% endif %}"
              href="{% url 'posts:profile' user.username %}"
              >Профиль</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:post_create' %}"
              >Новая запись</a
            >
          </li>
          <li class="nav-item">
            <a
              class="nav-link link-light"
              href="{% url 'users:password_change_form' %}"
              >Изменить пароль</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li class="nav-item">
            <a class="navbar-text nav-link" href="{% url 'posts:profile' user.username %}">Пользователь: {{ user.username }}</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'users:signup' %}"
              >Регистрация</a
            >
          </li>
        {% endif %} 
      {% endwith %}
    </ul>
  </div>
</nav>

yatube/templates/posts/create_post.html
{% extends 'base.html' %} 
{% block title %} 
  {% if is_edit %} Редактирование поста {% else %} Новый пост {% endif %} 
{% endblock title %} 
{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %} Редкатировать запись {% else %} Добавить запись {% endif %}
          </div>
          <div class="card-body">
            <form method="post">
              {% if form.non_field_errors %} 
                {% for error in non_field_errors %}  
                  <div class="alert alert-danger"> 
                    <strong>{{ error|escape }}</strong>
                  </div>
                {% endfor %}
              {% endif %}
              {% if form.errors %} 
                {% for field in form %} 
                  {% for error in field.errors %}  
                    <div class="alert alert-danger"> 
                      <strong>{{ error|escape }}</strong> 
                    </div> 
                  {% endfor %} 
                {% endfor %} 
              {% endif %}
              {% for field in form %}
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}{% if field.field.required %}*{% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                <p class="form-text text-muted">{{ field.help_text }}</p>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %} Сохранить {% else %} Добавить {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
{% block title %} 
  Записи сообщества {{ group }} 
{% endblock title %} 
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description|linebreaks }}</p>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>Автор: <a href="{% url 'posts:profile' post.author %}">@{{ post.author.get_full_name }}</a></li>
          <li>Дата публикации: {{ post.pub_date }}</li>
        </ul>
        <p>{{ post.text|linebreaks }}</p>
      </article>
      {% if not forloop.last %}
        <hr />
      {% endif %} 
    {% endfor %} 
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock content %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %} 
{% block title %} 
  Последние обновления на сайте 
{% endblock title %} 
{% block content %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    {% for post in page_obj %}
      <ul>
        <li>Автор: <a href="{% url 'posts:profile' post.author.username %}">@{{ post.author.get_full_name }}</a></li>
        <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
      </ul>
      <p>{{ post.text|linebreaks }}</p>
      {% if post.group %}
        <a href="{% url 'posts:group_posts' post.group.slug %}"
          >#{{ post.group.title }}</a
        >
      {% endif %} 
      {% if not forloop.last %}
        <hr />
      {% endif %} 
    {% endfor %} 
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %} 
{% block title %} 
  Пост {{ post.text|slice:":30" }} 
{% endblock title %} 
{% block content %}
  <div class="row m-3">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Дата публикации: {{ post.pub_date }}</li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: <a href="{% url 'posts:group_posts' post.group.slug %}">#{{ post.group.title }}</a>
          </li>
        {% endif %}
        <li class="list-group-item">Автор: <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a></li>
        <li
          class="list-group-item d-flex justify-content-between align-items-center"
        >
          Всего постов автора: <span>{{ post.author.posts.count }}</span>
        </li>
      </ul>
      {% if user == post.author %}
        <button type="submit" class="btn btn-primary">
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}"
            >Редактировать</a
          >
        </button>
      {% endif %}
    </aside>
    <article class="col-12 col-md-9">
      <p>{{ post.text|linebreaks }}</p>
    </article>
  </div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %} 
{% block title %} 
  Профайл пользователя {{ author.get_full_name }} 
{% endblock title %} 
{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ page_obj|length }}</h3>
    {% for post in page_obj %}
      <article class="text-decoration-none">
        <ul class="list-unstyled">
          <li class="text-decoration-none">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>Дата публикации: {{ post.pub_date }}</li>
        </ul>
        <p>{{ post.text|linebreaks }}</p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
      </article>
      {% if post.group %}
        <a href="{% url 'posts:group_posts' post.group.slug %}"> #{{ post.group.title }}</a>
      {% endif %}
      {% if not forloop.last %}
        <hr />
      {% endif %} 
    {% endfor %} 
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock content %}

yatube/users/templates/users/login.html
{% extends "base.html" %} 
{% block title %}
  Войти
{% endblock %} 
{% block content %} 
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Войти на сайт</div>
        <div class="card-body">
          {% if form.errors %} 
            {% for field in form %} 
              {% for error in field.errors %}
                <div class="alert alert-danger">{{ error|escape }}</div>
              {% endfor %} 
            {% endfor %} 
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">{{ error|escape }}</div>
            {% endfor %} 
          {% endif %}
          <form method="post" {% if action_url %} action="{% url action_url %}" {% endif %}>
            {% csrf_token %} 
            {% for field in form %}
              <div class="form-group row my-3"
                {% if field.field.required %} aria-required="true" {% else %} aria-required="false" {% endif %}>
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }} {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
                </label>
                <div>
                  {{ field|addclass:'form-control' }} 
                  {% if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted"
                    >
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">Войти</button>
              <a
                href="{% url 'users:password_reset_form' %}"
                class="btn btn-link"
              >
                Забыли пароль?
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/users/templates/users/password_reset_complete.html
{% extends 'base.html' %} 
{% block title %}
  Сброс пароля прошёл успешно
{% endblock %} 
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Восстановление пароля завершено</div>
          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="{% url 'users:login' %}">войти</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %} 
{% block title %}
  Новый пароль
{% endblock %} 
{% block content %} 
{% load user_filters %} 
  {% if validlink %}
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">Введите новый пароль</div>
            <div class="card-body">
              <form method="post" action="../users/lpassword_reset_confirm.html">
                <input type="hidden" name="csrfmiddlewaretoken" value="" />
                <div class="form-group row my-3 p-3">
                  <label for="id_new_password1">
                    Новый пароль
                    <span class="required text-danger">*</span>
                  </label>
                  <input
                    type="password"
                    name="new_password1"
                    class="form-control"
                    required
                    id="id_new_password1"
                  />
                  <small id="id_new_password1-help" class="form-text text-muted">
                    <ul>
                      <li>
                        Ваш пароль не должен совпадать с вашим именем или другой
                        персональной информацией или быть слишком похожим на неё.
                      </li>
                      <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                      <li>
                        Ваш пароль не может быть одним из широко распространённых
                        паролей.
                      </li>
                      <li>Ваш пароль не может состоять только из цифр.</li>
                    </ul>
                  </small>
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_new_password2">
                    Подтверждение нового пароля
                    <span class="required text-danger">*</span>
                  </label>
                  <input
                    type="password"
                    name="new_password2"
                    class="form-control"
                    required
                    id="id_new_password2"
                  />
                </div>
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-primary">
                    <a
                      href="{% url 'users:password_reset_complete' %}"
                      class="btn btn-primary"
                    >
                      Назначить новый пароль
                    </a>
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    <div>
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">Ошибка</div>
            <div class="card-body">
              <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %} 
{% endblock %}

yatube/users/templates/users/password_reset_form.html
{% extends 'base.html' %} 
{% block title %}
  Сброс пароля
{% endblock %} 
{% block content %} 
  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под
            которым вы регистрировались
          </div>
          <div class="card-body">
            <form method="post" action="../users/password_reset_form.html">
              <input type="hidden" name="csrfmiddlewaretoken" value="" />
              <div class="form-group row my-3 p-3">
                <label for="id_email">
                  Адрес электронной почты
                  <span class="required text-danger">*</span>
                </label>
                <input
                  type="email"
                  name="email"
                  maxlength="254"
                  class="form-control"
                  required
                  id="id_email"
                />
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  <a
                    href="{% url 'users:password_reset_done' %}"
                    class="btn btn-primary"
                  >
                    Сбросить пароль
                  </a>
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/users/templates/users/signup.html
{% extends "base.html" %} 
{% block title %}
  Зарегистрироваться
{% endblock %} 
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
        <div class="card-body">
          {% load user_filters %} 
          {% if form.errors %} 
            {% for field in form %} 
              {% for error in field.errors %}
                <div class="alert alert-danger">{{ error|escape }}</div>
              {% endfor %} 
            {% endfor %} 
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">{{ error|escape }}</div>
            {% endfor %} 
          {% endif %}
          <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %} 
            {% for field in form %}
              <div class="form-group row my-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }} 
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:'form-control' }} 
                {% if field.help_text %}
                  <small
                    id="{{ field.id_for_label }}-help"
                    class="form-text text-muted"
                  >
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}